import {TransactionT} from '@/constatns/types/types';
import {DateTime} from 'luxon'

export const transactions: TransactionT[] = [
    // August 2025 transactions
    {
        id: 89,
        createAt: DateTime.local(2025, 8, 5).toJSDate(),
        amount: 15000,
        currency: 'won',
        type: 'expense',
        memo: '외식',
    },
    {
        id: 90,
        createAt: DateTime.local(2025, 8, 10).toJSDate(),
        amount: 50000,
        currency: 'won',
        type: 'income',
        memo: '용돈',
    },
    {
        id: 91,
        createAt: DateTime.local(2025, 8, 15).toJSDate(),
        amount: 8000,
        currency: 'won',
        type: 'expense',
        memo: '영화',
    },
    {
        id: 92,
        createAt: DateTime.local(2025, 8, 20).toJSDate(),
        amount: 100000,
        currency: 'won',
        type: 'income',
        memo: '상여금',
    },
    {
        id: 93,
        createAt: DateTime.local(2025, 8, 25).toJSDate(),
        amount: 12000,
        currency: 'won',
        type: 'expense',
        memo: '택시',
    },
    // October 2025 transactions
    {
        id: 94,
        createAt: DateTime.local(2025, 10, 3).toJSDate(),
        amount: 25000,
        currency: 'won',
        type: 'expense',
        memo: '쇼핑',
    },
    {
        id: 95,
        createAt: DateTime.local(2025, 10, 8).toJSDate(),
        amount: 75000,
        currency: 'won',
        type: 'income',
        memo: '알바비',
    },
    {
        id: 96,
        createAt: DateTime.local(2025, 10, 15).toJSDate(),
        amount: 18000,
        currency: 'won',
        type: 'expense',
        memo: '식사',
    },
    {
        id: 97,
        createAt: DateTime.local(2025, 10, 22).toJSDate(),
        amount: 150000,
        currency: 'won',
        type: 'income',
        memo: '보너스',
    },
    {
        id: 98,
        createAt: DateTime.local(2025, 10, 28).toJSDate(),
        amount: 30000,
        currency: 'won',
        type: 'expense',
        memo: '선물',
    },

    {
        id: 0,
        createAt: DateTime.local(2025, 9, 12).toJSDate(),
        amount: 3000,
        currency: 'won',
        type: 'income',
        memo: '',
    },
    {
        id: 1,
        createAt: DateTime.local(2025, 9, 12).toJSDate(),
        amount: 2000,
        currency: 'won',
        type: 'expense',
        memo: '점심',
    },
    {
        id: 3,
        createAt: DateTime.local(2025, 9, 12).toJSDate(),
        amount: 8000,
        currency: 'won',
        type: 'expense',
        memo: '점심',
    },
    {
        id: 7,
        createAt: DateTime.local(2025, 9, 12).toJSDate(),
        currency: 'won',
        type: 'expense',
        memo: '점심',
        amount: 2000,
    },
    {
        id: 8,
        createAt: DateTime.local(2025, 9, 13).toJSDate(),
        currency: 'won',
        type: 'expense',
        memo: '점심',
        amount: 2000,
    },
    {
        id: 4,
        createAt: DateTime.local(2025, 9, 13).toJSDate(),
        amount: 2000,
        currency: 'won',
        type: 'expense',
        memo: '점심',
    },
    {
        id: 2,
        createAt: DateTime.local(2025, 9, 13).toJSDate(),
        amount: 4500,
        currency: 'won',
        type: 'income',
        memo: '헤헤이',
    },

    {
        id: 67,
        createAt: DateTime.local(2025, 9, 13).toJSDate(),
        amount: 4500,
        currency: 'won',
        type: 'income',
        memo: '헤헤이',
    },

    {
        id: 68,
        createAt: DateTime.local(2025, 9, 11).toJSDate(),
        amount: 4500,
        currency: 'won',
        type: 'income',
        memo: '헤헤이',
    },
    {
        id: 69,
        createAt: DateTime.local(2025, 9, 15).toJSDate(),
        amount: 1200,
        currency: 'won',
        type: 'expense',
        memo: '커피',
    },
    {
        id: 70,
        createAt: DateTime.local(2025, 9, 11).toJSDate(),
        amount: 5000,
        currency: 'won',
        type: 'income',
        memo: '용돈',
    },
    {
        id: 71,
        createAt: DateTime.local(2025, 9, 12).toJSDate(),
        amount: 3000,
        currency: 'won',
        type: 'expense',
        memo: '저녁',
    },
    {
        id: 72,
        createAt: DateTime.local(2025, 9, 18).toJSDate(),
        amount: 802300,
        currency: 'won',
        type: 'income',
        memo: '보너스',
    },
    {
        id: 73,
        createAt: DateTime.local(2025, 9, 16).toJSDate(),
        amount: 2500,
        currency: 'won',
        type: 'expense',
        memo: '간식',
    },
    {
        id: 74,
        createAt: DateTime.local(2025, 9, 16).toJSDate(),
        amount: 10000,
        currency: 'won',
        type: 'income',
        memo: '알바',
    },
    {
        id: 75,
        createAt: DateTime.local(2025, 9, 17).toJSDate(),
        amount: 4000,
        currency: 'won',
        type: 'expense',
        memo: '택시',
    },
    {
        id: 76,
        createAt: DateTime.local(2025, 9, 17).toJSDate(),
        amount: 6000,
        currency: 'won',
        type: 'income',
        memo: '환급',
    },
    {
        id: 77,
        createAt: DateTime.local(2025, 9, 18).toJSDate(),
        amount: 3500,
        currency: 'won',
        type: 'expense',
        memo: '영화',
    },
    {
        id: 78,
        createAt: DateTime.local(2025, 9, 18).toJSDate(),
        amount: 7000,
        currency: 'won',
        type: 'income',
        memo: '상금',
    },
    {
        id: 79,
        createAt: DateTime.local(2025, 9, 19).toJSDate(),
        amount: 2200,
        currency: 'won',
        type: 'expense',
        memo: '아이스크림',
    },
    {
        id: 80,
        createAt: DateTime.local(2025, 9, 19).toJSDate(),
        amount: 9000,
        currency: 'won',
        type: 'income',
        memo: '추가수입',
    },
    {
        id: 81,
        createAt: DateTime.local(2025, 9, 20).toJSDate(),
        amount: 1800,
        currency: 'won',
        type: 'expense',
        memo: '빵',
    },
    {
        id: 82,
        createAt: DateTime.local(2025, 9, 20).toJSDate(),
        amount: 11000,
        currency: 'won',
        type: 'income',
        memo: '용돈',
    },
    {
        id: 83,
        createAt: DateTime.local(2025, 9, 21).toJSDate(),
        amount: 2700,
        currency: 'won',
        type: 'expense',
        memo: '음료',
    },
    {
        id: 84,
        createAt: DateTime.local(2025, 9, 21).toJSDate(),
        amount: 13000,
        currency: 'won',
        type: 'income',
        memo: '보너스',
    },
    {
        id: 85,
        createAt: DateTime.local(2025, 9, 22).toJSDate(),
        amount: 3200,
        currency: 'won',
        type: 'expense',
        memo: '점심',
    },
    {
        id: 86,
        createAt: DateTime.local(2025, 9, 22).toJSDate(),
        amount: 14000,
        currency: 'won',
        type: 'income',
        memo: '알바',
    },
    {
        id: 87,
        createAt: DateTime.local(2025, 9, 23).toJSDate(),
        amount: 2100,
        currency: 'won',
        type: 'expense',
        memo: '과자',
    },
    {
        id: 88,
        createAt: DateTime.local(2025, 9, 23).toJSDate(),
        amount: 15000,
        currency: 'won',
        type: 'income',
        memo: '추가수입',
    }


];